<a href="https://colab.research.google.com/github/Sonia-devi/FINAL_RESEARCH_PROJECT/blob/main/Descriptive_statistics_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import scipy.stats as stats
from matplotlib import pyplot as plt
import seaborn as sns
from pandas import Series, DataFrame

In [ ]:
#Load the Dataset
df = pd.read_excel(r"/content/transformation of dataset 1.xlsx")

In [ ]:
df.head(10)

,Age Group,Handedness,Gender,Job Function,Weight,Height,BMI,Aviation Sector,Flight Hours,Flight Type,...,Breathing Difficulties,Cough and/or snoring,Cold difficulties,Hot difficulties,Bad dreams,Pain difficulties,Other difficulties,Social Activity Sleepiness,Sustained Enthusiasm Difficulties,Sleep Quality
0,1,1,0,1,102.0,1.84,30.127599,1.0,5000.0,1.0,...,0,1,0,1.0,0.0,0,0.0,0.0,0,Fairly good
1,3,1,0,1,82.7,1.78,26.101502,1.0,4200.0,1.0,...,0,0,0,0.0,1.0,3,0.0,0.0,3,Fairly bad
2,1,1,0,1,80.0,2.00,20.000000,1.0,6100.0,4.0,...,0,0,0,0.0,0.0,0,3.0,1.0,3,Fairly bad
3,1,1,0,1,80.0,1.75,26.122449,1.0,6000.0,4.0,...,0,0,0,0.0,0.0,0,1.0,1.0,0,Fairly good
4,0,1,0,1,89.0,1.78,28.089888,1.0,1000.0,2.0,...,1,0,0,1.0,1.0,0,3.0,1.0,2,Fairly bad
5,1,1,1,2,70.0,1.62,26.672763,1.0,NaN,NaN,...,0,0,2,2.0,1.0,1,0.0,0.0,3,Fairly good
6,3,1,0,1,89.0,1.73,29.737044,1.0,12500.0,1.0,...,0,0,0,0.0,0.0,0,0.0,0.0,3,Fairly bad
7,2,2,0,1,78.0,1.76,25.180785,1.0,14500.0,4.0,...,0,0,0,0.0,0.0,0,0.0,0.0,2,Fairly good
8,2,1,0,1,65.0,1.80,20.061728,1.0,3000.0,4.0,...,0,0,0,1.0,1.0,0,1.0,0.0,3,Fairly good
9,0,1,0,1,64.0,1.69,22.408179,1.0,200.0,4.0,...,0,0,0,0.0,0.0,0,0.0,1.0,3,Fairly good

In [ ]:
df.describe()

,Age Group,Handedness,Gender,Job Function,Weight,Height,BMI,Aviation Sector,Flight Hours,Flight Type,...,Bathroom Problems,Breathing Difficulties,Cough and/or snoring,Cold difficulties,Hot difficulties,Bad dreams,Pain difficulties,Other difficulties,Social Activity Sleepiness,Sustained Enthusiasm Difficulties
count,295.000000,295.000000,295.000000,295.000000,291.000000,289.000000,287.000000,291.000000,166.000000,205.000000,...,295.000000,295.000000,295.000000,295.000000,293.000000,294.000000,295.000000,293.000000,294.000000,295.000000
mean,1.884746,0.894915,0.233898,2.423729,81.473952,1.763744,26.151228,1.439863,7755.638554,2.263415,...,1.335593,0.220339,0.294915,0.386441,0.795222,0.649660,0.552542,0.955631,0.299320,1.755932
std,1.121954,0.394444,0.431975,1.812686,16.921862,0.089251,4.893273,0.817265,5287.463592,1.248088,...,1.177707,0.635348,0.776663,0.773599,1.091237,0.975668,0.923863,1.182671,0.695328,1.027558
min,0.000000,0.000000,0.000000,1.000000,52.000000,1.500000,17.577069,1.000000,56.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,0.000000,1.000000,70.500000,1.700000,23.219689,1.000000,3500.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,2.000000,1.000000,0.000000,1.000000,80.000000,1.780000,25.712199,1.000000,7020.000000,2.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,3.000000,1.000000,0.000000,4.000000,90.000000,1.830000,27.763900,2.000000,11875.000000,3.000000,...,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,3.000000
max,5.000000,2.000000,2.000000,6.000000,190.000000,2.000000,65.743945,5.000000,22000.000000,6.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000

In [ ]:
df.sample(frac=0.05)

,Age Group,Handedness,Gender,Job Function,Weight,Height,BMI,Aviation Sector,Flight Hours,Flight Type,...,Breathing Difficulties,Cough and/or snoring,Cold difficulties,Hot difficulties,Bad dreams,Pain difficulties,Other difficulties,Social Activity Sleepiness,Sustained Enthusiasm Difficulties,Sleep Quality
99,2,1,0,1,60.0,1.72,20.281233,1.0,8974.0,4.0,...,1,0,0,0.0,1.0,0,0.0,0.0,0,Fairly good
17,2,1,0,1,91.0,1.73,30.405293,1.0,8000.0,1.0,...,0,1,0,3.0,1.0,3,0.0,0.0,3,Very good
93,3,1,0,1,110.0,1.78,34.717839,1.0,7800.0,4.0,...,1,3,0,0.0,0.0,2,2.0,0.0,2,Very bad
8,2,1,0,1,65.0,1.80,20.061728,1.0,3000.0,4.0,...,0,0,0,1.0,1.0,0,1.0,0.0,3,Fairly good
126,3,1,0,1,116.0,1.88,32.820281,1.0,16000.0,2.0,...,1,0,0,1.0,0.0,0,0.0,0.0,2,Fairly good
238,2,1,1,3,74.0,1.60,28.906250,2.0,NaN,NaN,...,0,0,0,0.0,0.0,0,3.0,0.0,3,Fairly bad
120,1,1,0,1,52.0,1.72,17.577069,1.0,6000.0,2.0,...,0,0,1,1.0,3.0,0,0.0,0.0,2,Fairly good
216,3,1,1,4,58.0,1.65,21.303949,2.0,NaN,NaN,...,0,0,0,2.0,0.0,0,0.0,0.0,2,Very good
146,2,1,0,1,82.0,NaN,NaN,NaN,12500.0,4.0,...,0,0,0,0.0,0.0,0,1.0,0.0,2,Fairly bad
141,0,1,1,1,NaN,NaN,NaN,1.0,5500.0,2.0,...,0,0,0,0.0,0.0,0,0.0,0.0,2,Fairly good
105,3,1,0,1,71.0,1.78,22.408787,1.0,13500.0,1.0,...,0,0,0,0.0,0.0,0,1.0,0.0,1,Very good
209,1,1,0,4,78.0,1.75,25.469388,2.0,NaN,NaN,...,0,0,1,3.0,3.0,3,2.0,1.0,2,Very bad
66,4,1,0,1,90.0,1.93,24.161722,1.0,10000.0,4.0,...,0,0,0,0.0,1.0,2,0.0,0.0,1,Fairly good
184,5,1,0,2,96.0,1.94,25.507493,2.0,NaN,NaN,...,0,0,0,3.0,0.0,0,0.0,0.0,0,Fairly good
26,1,1,0,1,86.0,1.75,28.081633,1.0,11000.0,1.0,...,0,0,3,0.0,0.0,0,0.0,1.0,3,Fairly good

In [ ]:
sample_data = df.sample(frac=0.05)

In [ ]:
sample_data.describe()

,Age Group,Handedness,Gender,Job Function,Weight,Height,BMI,Aviation Sector,Flight Hours,Flight Type,...,Bathroom Problems,Breathing Difficulties,Cough and/or snoring,Cold difficulties,Hot difficulties,Bad dreams,Pain difficulties,Other difficulties,Social Activity Sleepiness,Sustained Enthusiasm Difficulties
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,7.000000,10.00000,...,15.000000,15.000000,15.0,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,2.200000,0.800000,0.400000,2.733333,80.994667,1.744000,26.777798,1.533333,6848.571429,1.70000,...,1.066667,0.400000,0.0,0.533333,0.600000,1.133333,0.866667,1.133333,0.266667,1.866667
std,0.941124,0.414039,0.507093,1.980861,16.903799,0.090063,3.197371,0.833809,5965.476870,1.05935,...,1.032796,1.055597,0.0,0.915475,1.121224,1.407463,1.187234,1.187234,0.593617,0.990430
min,1.000000,0.000000,0.000000,1.000000,60.000000,1.640000,22.308150,1.000000,180.000000,1.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.500000,1.000000,0.000000,1.000000,70.500000,1.680000,24.756100,1.000000,2200.000000,1.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.500000
50%,2.000000,1.000000,0.000000,2.000000,78.000000,1.750000,26.026530,1.000000,4500.000000,1.00000,...,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000
75%,3.000000,1.000000,1.000000,4.000000,87.500000,1.780000,29.365093,2.000000,12680.000000,2.00000,...,1.500000,0.000000,0.0,1.000000,0.500000,3.000000,1.000000,2.000000,0.000000,2.500000
max,4.000000,1.000000,1.000000,6.000000,130.000000,2.000000,32.500000,4.000000,13500.000000,4.00000,...,3.000000,3.000000,0.0,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,3.000000

In [ ]:
# Calculate descriptive statistics for BMI
BMI_stats = df["BMI"].describe()
print("BMI descriptive statistics:",BMI_stats)

BMI descriptive statistics: count    287.000000
mean      26.151228
std        4.893273
min       17.577069
25%       23.219689
50%       25.712199
75%       27.763900
max       65.743945
Name: BMI, dtype: float64

In [ ]:
# Calculate descriptive statistics for Bad dreams
Bad_dreams_stats = df["Bad dreams"].describe()
print("Bad dreams descriptive statistics:", Bad_dreams_stats)

Bad dreams descriptive statistics: count    294.000000
mean       0.649660
std        0.975668
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        3.000000
Name: Bad dreams, dtype: float64

In [ ]:
# Calculate descriptive statistics for Job Function
Job_Function_stats = df["Job Function"].describe()
print("Job Function descriptive statistics:", Job_Function_stats)

Job Function descriptive statistics: count    295.000000
mean       2.423729
std        1.812686
min        1.000000
25%        1.000000
50%        1.000000
75%        4.000000
max        6.000000
Name: Job Function, dtype: float64

In [ ]:
# Calculate descriptive statistics for Aviation Sector
Aviation_Sector_stats = df["Aviation Sector"].describe()
print("Aviation Sector descriptive statistics:", Aviation_Sector_stats)

Aviation Sector descriptive statistics: count    291.000000
mean       1.439863
std        0.817265
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
Name: Aviation Sector, dtype: float64

In [ ]:
# Calculate descriptive statistics for Flight Hours
Flight_Hours_stats = df["Flight Hours"].describe()
print("Flight Hours descriptive statistics:", Flight_Hours_stats)

Flight Hours descriptive statistics: count      166.000000
mean      7755.638554
std       5287.463592
min         56.000000
25%       3500.000000
50%       7020.000000
75%      11875.000000
max      22000.000000
Name: Flight Hours, dtype: float64

Hypothesis Testing

Research Question : How sleep quailty